[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "neural_interference"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test-mitsuba = { cmd = "echo $PYTHONPATH && python -m pytest", cwd = "mitsuba3/build/build-mitsuba", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
debug-mitsuba = { cmd = "echo $PYTHONPATH && gdb --args python -m pytest", cwd = "mitsuba3/build", env = { PYTHONPATH = "python:$PYTHONPATH" }, depends-on = [
    "build-mitsuba",
] }
build-mitsuba = { cwd = "mitsuba3/build/", cmd = "ninja", depends-on = [
    "configure-mitsuba",
] }
configure-mitsuba = { cmd = "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -S ./mitsuba3/ -B mitsuba3/build" }
clean-mitsuba = { cmd = "rm -r build", cwd = "mitsuba3" }

[dependencies]
python = "3.12.*"
gcc = { version = "13.2.*", channel = "conda-forge" }
gxx = { version = "13.2.*", channel = "conda-forge" }
pytorch-cuda = { version = "12.4.*", channel = "pytorch" }
pytorch = { version = ">=2.4.1,<3", channel = "pytorch" }
torchvision = { version = ">=0.19.1,<0.20", channel = "pytorch" }
torchaudio = { version = ">=2.4.1,<3", channel = "pytorch" }
zlib = "1.3.1"
libcxx = ">=19.1.1,<20"
libcxx-devel = ">=19.1.1,<20"
libcxxabi = ">=19.1.1,<20"

pip = ">=24.2,<25"

cuda = "*"

ipython = ">=8.28.0,<9"
matplotlib = ">=3.9.2,<4"
numpy = ">=2.1.2,<3"
omegaconf = ">=2.3.0,<3"
pytest = ">=8.3.3,<9"

[pypi-options]
no-build-isolation = ["tinycudann"]

[pypi-dependencies]
tensorboardx = "*"
mitsuba = ">=3.6.0, <4"
tinycudann = { git = "https://github.com/NVlabs/tiny-cuda-nn.git", subdirectory = "bindings/torch", rev = "c91138bcd4c6877c8d5e60e483c0581aafc70cce" }

[activation]
scripts = ["mitsuba3/build/setpath.sh"]
# PYTHONPATH = "mitsuba3/build/python:$PYTHONPATH"

[target.linux-64.activation.env]
# Have to expose /lib64 for libcuda.so (cuda driver)
LIBRARY_PATH = "/lib64"
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
