# Implicit System Requirements:
# - bear


[project]
authors = ["Christian Döring <christian.doering@tum.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]

[dependencies]
cmake = "3.28.*"
gcc = "13.2.*"
gxx = "13.2.*"
ccache = ">=4.10.1,<5"
gdb = ">=15.1,<16"
ninja = ">=1.12.1,<2"
clang = "18.*"
pkg-config = ">=0.29.2,<0.30"
curl = ">=8.14.1,<9"

zlib = "==1.3.1"
embree = ">=4.3.3,<5"

clangxx = "18.*"
libcxx = "18.*"
libcxx-devel = "18.*"
libcxxabi = "18.*"
llvm = "18.*"
llvmdev = "18.*"
compiler-rt = "18.*"  # provides asan

lld = "18.*"
mold = ">=2.35.1,<3"

python = "3.12.*"
pytest = ">=8.3.3,<9"
numpy = ">=2.1.2,<3"
tqdm = ">=4.67.1,<5"

cuda = "*"
nsight-compute = ">=2025.2.0,<2026"
furo = ">=2024.8.6,<2025"

pip = ">=25.1.1,<26"

libegl = ">=1.7.0,<2"
libegl-devel = ">=1.7.0,<2"

[target.linux-64.activation]
scripts = ["mitsuba3/build-mitsuba/setpath.sh"]

[target.linux-64.activation.env]
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
CMAKE_PREFIX_PATH = "$CONDA_PREFIX"
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
CUDA_TOOLKIT_ROOT_DIR = "$CONDA_PREFIX/lib"
# PYTHONPATH = "python:$PYTHONPATH"

[pypi-dependencies]
notebook = ">=7.4.2, <8"
ipywidgets = ">=8.1.7, <9"
matplotlib = ">=3.10.1, <4"
cholespy = ">=2.1.0, <3"

torch = "*"
torchvision = ">=0.20.1, <0.21"
torchaudio = ">=2.5.1, <3"
gpytoolbox = ">=0.3.0, <0.4"

# docs
sphinx = ">=8.2.3, <9"
sphinxcontrib-katex = ">=0.9.10, <0.10"
furo = "*"
enum-tools = { version = ">=0.13.0, <0.14", extras = ["sphinx"] }
sphinxcontrib-svg2pdfconverter = ">=1.3.0, <2"

# Sionna specific
esbonio = ">=0.16.5, <0.17"
importlib-resources = ">=6.5.2, <7"
pythreejs = ">=2.4.2, <3"
scipy = ">=1.15.3, <2"
typing-extensions = "*"
nvtx = ">=0.2.12, <0.3"
omegaconf = ">=2.3.0, <3"
commentjson = ">=0.9.0, <0.10"
polyscope = ">=2.4.0, <3"
jupytext = ">=1.17.2, <2"
